# Generated by Django 3.1.7 on 2021-03-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.ImageField(upload_to='img/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.IntegerField(default=0)),
                ('lat', models.IntegerField(default=0)),
                ('elevation', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
