# Generated by Django 3.1.7 on 2021-03-21 02:04

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0003_auto_20210321_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='target',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='target',
            name='long',
        ),
        migrations.AddField(
            model_name='observation',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, 0.0), dim=3, srid=4326),
        ),
        migrations.AddField(
            model_name='target',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, 0.0), dim=3, srid=4326),
        ),
    ]
