# Generated by Django 3.1.7 on 2021-03-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0004_auto_20210321_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='coord',
        ),
        migrations.AddField(
            model_name='observation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
