# Generated by Django 3.1.7 on 2021-03-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0005_auto_20210321_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
