# Generated by Django 3.1.7 on 2021-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0007_auto_20210321_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
