version: "3.7"
services:

  web:
    build: .
    container_name: web
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres_GHG
    image: mdillon/postgis
    env_file: .env
    ports:
      - "5432:5432"


